# Generated by Django 3.2.8 on 2021-11-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=255)),
                ('parent_case', models.CharField(blank=True, max_length=255, null=True)),
                ('sts_agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Type', models.CharField(blank=True, max_length=255, null=True)),
                ('session_dt_created', models.CharField(blank=True, max_length=255, null=True)),
                ('case_severity_level', models.CharField(blank=True, max_length=255, null=True)),
                ('session_time', models.CharField(blank=True, max_length=40, null=True)),
                ('account_name_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('case_support_mission', models.CharField(blank=True, max_length=255, null=True)),
                ('case_opened_date', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('case_status', models.CharField(blank=True, max_length=254, null=True)),
                ('case_owner', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PEModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PE_name', models.CharField(max_length=255)),
                ('cnickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
                ('name_per_ilc', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
    ]
