# Generated by Django 3.2.8 on 2021-10-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=255)),
                ('name_per_ilc', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
    ]
