# Generated by Django 3.2.8 on 2021-10-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseViews',
            new_name='CaseView',
        ),
    ]
