# Generated by Django 3.2.8 on 2021-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField()),
                ('parent_case', models.IntegerField()),
                ('sts_agent_name', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('case_severity_level', models.CharField(max_length=255)),
                ('session_time', models.DecimalField(decimal_places=3, max_digits=4)),
                ('account_name_formula', models.CharField(max_length=255)),
                ('case_support_mission', models.CharField(max_length=255)),
                ('case_opened_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('pit', models.CharField(max_length=255)),
                ('case_status', models.CharField(max_length=255)),
                ('case_owner', models.CharField(max_length=255)),
            ],
        ),
    ]
