# Generated by Django 3.2.8 on 2021-10-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0002_rename_caseviews_caseview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseview',
            name='session_time',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4),
        ),
    ]
