# Generated by Django 3.2.8 on 2021-11-06 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0002_uploadresourcemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcenamemodel',
            name='role',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadresourcemodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
