# Generated by Django 3.2.8 on 2021-11-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0003_auto_20211106_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='name_per_ilc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='resource_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
