# Generated by Django 3.2.8 on 2021-10-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0003_alter_caseview_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseview',
            name='Type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='session_time',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='sts_agent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
