# Generated by Django 3.2.8 on 2021-10-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0003_auto_20211011_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseview',
            name='pit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
