# Generated by Django 3.2.8 on 2021-11-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0004_auto_20211106_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tot_con_price', models.IntegerField(default=0)),
                ('max_threshold', models.IntegerField(default=100)),
            ],
        ),
    ]
