# Generated by Django 3.2.8 on 2021-10-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0004_auto_20211011_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseview',
            old_name='pit',
            new_name='product',
        ),
    ]
