# Generated by Django 3.2.8 on 2021-10-28 13:33

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0004_auto_20211028_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='cost',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='name_per_ilc',
            field=models.CharField(default=datetime.datetime(2021, 10, 28, 13, 33, 40, 976812, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='resource_name',
            field=models.CharField(max_length=255),
        ),
    ]
