# Generated by Django 3.2.8 on 2021-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0005_rename_pit_caseview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseview',
            name='parent_case',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
