# Generated by Django 3.2.8 on 2021-10-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0005_alter_caseview_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseview',
            name='session_time',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
