# Generated by Django 3.2.8 on 2021-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0005_auto_20211028_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='name_per_ilc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resourcenamemodel',
            name='resource_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
