# Generated by Django 3.2.8 on 2021-10-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0006_alter_caseview_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseview',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
