# Generated by Django 3.2.8 on 2021-11-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0006_threshold_acc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='rsc_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
