# Generated by Django 3.2.8 on 2021-11-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0007_threshold_rsc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold',
            name='tot_con_price',
        ),
    ]
