# Generated by Django 3.2.8 on 2021-11-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0008_remove_threshold_tot_con_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='General',
        ),
        migrations.AlterField(
            model_name='threshold',
            name='max_threshold',
            field=models.IntegerField(default=800),
        ),
    ]
