# Generated by Django 3.2.8 on 2021-10-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0008_auto_20211014_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseview',
            name='case_support_mission',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
