# Generated by Django 3.2.8 on 2021-10-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PERs', '0009_alter_caseview_case_support_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseview',
            name='account_name_formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='case_opened_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='case_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='case_severity_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='case_status',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='caseview',
            name='session_dt_created',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
